### ISSUE TITLE
UOJ 还没开源

### ISSUE THREAD

**Issue by vfleaking** [vfleaking/uoj#1]
还有些锅解决之后才能把uoj代码传上来

**Comment by Menci** [comment]
Why MIT instead of GPL?

**Comment by Too-Naive** [comment]
同问
![](https://cloud.githubusercontent.com/assets/16496671/14854755/80a24440-0cc3-11e6-90c8-549f0c052ef3.jpg)

**Comment by ziqin** [comment]
@Menci
我认为 MIT License 大法好。GPL虽有许多限制，但中国司法界貌似未曾承认过其有效性。不如来个简洁明了限制少的。

**Comment by Ruanxingzhi** [comment]
MIT License 大法好。

**Comment by wuzhuangtai00** [comment]
敲碗等开源>_<

**Comment by Ruanxingzhi** [comment]
敲碗等开源>_<

**Comment by MascoSkray** [comment]
开源了就可以自己fix issue了！

**Comment by MascoSkray** [comment]
开源了就可以自己fix issue了！

**Comment by Ruanxingzhi** [comment]
敲碗等开源>_<

**Comment by MascoSkray** [comment]
花儿都谢了。。。

**Comment by fjzzq2002** [comment]
敲碗等开源>_<

**Comment by MascoSkray** [comment]
敲碗等开源>_<

**Comment by Too-Naive** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/14854755/80a24440-0cc3-11e6-90c8-549f0c052ef3.jpg)

**Comment by vfleaking** [comment]
现在 UOJ 开源了！
