### ISSUE TITLE
如何跳过Jdk的安装?

### ISSUE THREAD

**Issue by Too-Naive** [vfleaking/uoj#10]
个人认为的话 对于普通的小学校 java并不是学习的主流吧 所以... 似乎也并没有必要列到默认的安装上？

**Comment by vfleaking** [comment]
First please download JDK7u76 and JDK8u31, and put them to docker/jdk-7u76-linux-x64.tar.gz and docker/jdk-8u31-linux-x64.tar.gz. These two compressed files are used by judge_client for judging Java program. If you are too lazy to download these two huge files, you can simply place two empty .tar.gz files there.

已经在 README 里写了
