### ISSUE TITLE
比赛如何邀请人

### ISSUE THREAD

**Issue by PythonSmall-Q** [vfleaking/uoj#106]
您好，我是一位用户。我想问一下UOJ的比赛如何邀请人加入。我这边无法设置谁可以参与。从这里点击：
![image](https://user-images.githubusercontent.com/106425289/216241736-96c1bd0a-698e-46ab-8e40-581db563768e.png)
用户端会显示
![image](https://user-images.githubusercontent.com/106425289/216241702-7d7a64e7-6517-4216-9005-5366f529f363.png)
![image](https://user-images.githubusercontent.com/106425289/216241736-96c1bd0a-698e-46ab-8e40-581db563768e.png)
我想问一下如何设置
@vfleaking

**Comment by PythonSmall-Q** [comment]
我急于像修复这个问题，毕竟已经因为各种技术问题把比赛从一月份延期到二月了

**Comment by PythonSmall-Q** [comment]
@roastduck @panda2134 @vfleaking @Pisces000221 我真的很急，比赛已经开始了，我的QQ消息都堆满了。全是告诉我不能进入比赛

**Comment by vfleaking** [comment]
我有点困惑，为什么报名人数是0人？之前大家没有报名吗

**Comment by PythonSmall-Q** [comment]
什么意思，不太理解

**Comment by PythonSmall-Q** [comment]
毕竟初中学生都还小，让他们一直看OJ不太现实，毕竟不可能让所有人一起点报名

**Comment by vfleaking** [comment]
比赛过程中开放报名需要自己改代码。鉴于你现在情况比较紧急，建议你把比赛的开始时间调到14:00，然后让大家赶紧报名，14:00再正式开赛

**Comment by PythonSmall-Q** [comment]
哦哦好，谢谢

**Comment by PythonSmall-Q** [comment]
那我想问一下需要改哪一些代码。docker进mysql似乎一直说permission denied，说不能以无密码的root的形式进入

**Comment by vfleaking** [comment]
不用进 mysql。改网页端代码就行

https://github.com/UniversalOJ/UOJ-System/blob/0d931e270b425b35fabb421ea21043ba2aaf9786/web/app/controllers/contest_registration.php#L10
这里 `!= CONTEST_NOT_STARTED` 改成 `<= CONTEST_IN_PROGRESS`

https://github.com/UniversalOJ/UOJ-System/blob/0d931e270b425b35fabb421ea21043ba2aaf9786/web/app/controllers/contest_inside.php#L15
这里 `becomeMsgPage(...);` 改成 `header("Location: /contest/{$contest['id']}/register"); die();`

**Comment by vfleaking** [comment]
> 我急于像修复这个问题，毕竟已经因为各种技术问题把比赛从一月份延期到二月了

太惨了……刚上手确实会遇到不少麻烦，不好意思。不过你可以加 UOJ 开源群的，平时有问题可以在群里问，也可以私聊找我。群号是 590822951

**Comment by PythonSmall-Q** [comment]
嗯嗯，再打扰一下，网页端代码怎么改，教程里面没有……：-（

**Comment by vfleaking** [comment]
应该是在 `/opt/uoj/web/` 这个目录下，找到我上面链接里的两个文件，然后改改就好

我主要在维护官网版，你用的是开源社区版。UOJ 的基本架构可以在这里找到：https://vfleaking.github.io/uoj/dev/ 官网版和开源社区版是类似的，只有些微小的差异

**Comment by PythonSmall-Q** [comment]
好，我试试。有问题再联系您，谢谢啦

**Comment by vfleaking** [comment]
好的 :)
