### ISSUE TITLE
（猜想的）Docker的正确使用姿势

### ISSUE THREAD

**Issue by t123yh** [vfleaking/uoj#14]
应该有三个容器：uoj_web，judge_client和mysql。
其中uoj_web直接继承php的源，mysql直接继承mysql的源。（最好）不要用shell弄出来的容器。
uoj_web开一个volume，用于存储测是数据；mysql开一个volume，用于存放数据库文件。
初始化数据库应由Web app来完成，当然直接执行 sql 脚本也是可以的。
先写在这吧，我知道实现起来多少会有些困难。

![default](https://cloud.githubusercontent.com/assets/8972552/19068928/1d1da574-8a57-11e6-8aef-26254f240305.png)

**Comment by yqszxx** [comment]
我倒是觉得环境不应该直接放在github里，只把评测程序、网页程序放上来就好。

**Comment by MascoSkray** [comment]
确实应该分离才“正规”，这样的UOJ是把容器当轻量级虚拟机使...
不过这社区版下一步已经考虑做分离了，docker-compose搞一下。
