### ISSUE TITLE
uoj文档问题

### ISSUE THREAD

**Issue by Too-Naive** [vfleaking/uoj#19]
文档可以全部编辑在wiki中 而且用clone也很方便
个人认为文档可以不必放在uoj源代码中

**Comment by vfleaking** [comment]
什么鬼。。。代码和文档放在一个版本库然后保持一致不是很妙吗 [手动思考熊]

很多开源项目都是这样放的吧。。。在我有限的认知范围内。。。

**Comment by imcaffrey** [comment]
@Too-Naive 比如 https://github.com/nodejs/node/tree/master/doc
