### ISSUE TITLE
开启内网穿透后无法正常访问

### ISSUE THREAD

**Issue by dingyx99** [vfleaking/uoj#31]
我们在搭建完之后，为了方便不在学校的人能随时AK，就买了花生棒开内网穿透，并绑定域名。机房内电脑采用Hosts直接指向服务器来访问，都写进config里面了。结果今天突然看，内网域名404，只有穿透的余名可以访问~~求解怎么回事
![image](https://cloud.githubusercontent.com/assets/11485117/19210683/a68bb4b0-8d5c-11e6-8403-ad227ce842f7.png)
![image](https://cloud.githubusercontent.com/assets/11485117/19210689/bd83194c-8d5c-11e6-89e7-52b107165a04.png)

**Comment by MascoSkray** [comment]
因为访问的域名只能按照.config.php里面设置的域名来访问。解决办法就是将hosts里面的域名和花生壳域名设置成一样的。
