### ISSUE TITLE
注册登陆界面均显示“页面已过期”

### ISSUE THREAD

**Issue by yqszxx** [vfleaking/uoj#33]
按照标准安装完，修改配置到内网IP裸奔模式，注册和登陆界面都显示“页面已过期”，怀疑csrf问题？

**Comment by Ruanxingzhi** [comment]
See also: [关于内网搭建的问题 · Issue#11](https://github.com/vfleaking/uoj/issues/11)

**Comment by yqszxx** [comment]
#34

**Comment by yqszxx** [comment]
#34
