### ISSUE TITLE
使用最新commit的uoj之后注册/登录出现问题..

### ISSUE THREAD

**Issue by AD1024** [vfleaking/uoj#38]
不知道是哪里姿势不太对，今天新建好的image放在container里run之后，注册时提示“页面已过期”。后来蜜汁没有这个问题了...但是登录不上去(也是“页面已过期”)
> By the way: 在**a9f1af7504a8e2806d3acfc8dff3090eda864d55** 这个commit之前的代码没有这个问题....
> >FYI: 看似是cookie出现了些神奇的问题....(同学用ubuntu是ok的，服务器端注册是不ok的；我的MacBook也是有问题的...)

**Comment by vfleaking** [comment]
QAQ 手抽啦
已 fix
