### ISSUE TITLE
hack成功却未能上传数据

### ISSUE THREAD

**Issue by vfleaking** [vfleaking/uoj#4]
hacker提交的测试数据太大导致超过apache post文件的限制，加数据的请求被服务器拒绝

**Comment by skyline48** [comment]
1是不是可以将大数据变成一个创造数据的程序？
2是不是可以将大数据分成几份传上去，然后合并？
我口胡的。

**Comment by Ruanxingzhi** [comment]
是否可以通过改php.ini来避免这个问题？
我口胡的。

**Comment by vfleaking** [comment]
43280f92d6ee90e2250f9133772e3880ea10b0be 修好了这个问题。。其实是因为用户交的是输入文件，而测评机向服务器交的是 输入 + 输出，所以输入文件符合文件大小要求不一定测评机也能顺利提交。所以我大概。。凑合着修了下吧。。
