### ISSUE TITLE
希望UOJ能尽快补全文档...

### ISSUE THREAD

**Issue by riteme** [vfleaking/uoj#40]
交互题究竟有什么黑科技导致其文档一直坑着.....
捆绑测试的搞法还是从民间学来的......
UOJ是个好OJ但是没有文档就比较haha了......

**Comment by vfleaking** [comment]
其实……挺难过的……每次想搞搞 UOJ 都会发现只能熬夜才能有时间……
又到这个点了，不过总算把交互题的文档补上了，还加了些样题。

**Comment by quietshu** [comment]
VFK 辛苦了 👍

**Comment by samcompu** [comment]
辛苦了，只是为傻么还不用 git 啊～

**Comment by vfleaking** [comment]
虽然已经6年过去了，但最新的commit中我补全了很多文档啦

https://vfleaking.github.io/uoj/
