### ISSUE TITLE
C++11的评测中多线程导致Dangerous Syscall

### ISSUE THREAD

**Issue by riteme** [vfleaking/uoj#42]
vfk大大把交互题的文档写好后，我尝试去加交互题，但是有一个比较蛋疼的问题就是我的交互库使用了多线程来评测结果......
g++ 4.8.4中开启了`-std=c++11`后，虽然可以使用`<thread>`，可以编译通过，但是一但运行线程就会被`abort`掉，然后在评测结果里的表现就是`Dangerous Syscall`。
为了使g++ 4.8.4真正支持多线程，需要加上`-pthread`参数。

另外想知道如何手动更新`judge_client`......我们找到了judger的编译文件的地方，修改了编译参数，但是`make`后好像没效果......

给一个多线程的样例程序：

```c++
#include <cstdio>
#include <cstdlib>

#include <thread>

using namespace std;

int main() {
    thread t([]() {printf("OK\n"); exit(0);});
    t.join();

    return 0;
}
```

编译

```shell
g++ www.cpp -std=c++11 -pthread
```

**Comment by vfleaking** [comment]
对……交互库是和选手程序绑一起编译的，所以肯定也是不能给开线程的权限的……（咦是怎样的情况下交互库必须开多线程才可以呢？

更新 judge_client 的正确姿势是用 svn checkout 一份出来改完了然后 commit。（不过你这样全手动 make 的话理论也是应该会起效的呀，奇怪……

**Comment by Ruanxingzhi** [comment]
@vfleaking riteme的题很神，他需要**一个线程用来跑程序，一个线程用来计时**，最后以限定时间内选手的程序**处理了多少个询问**来评分……233

**Comment by riteme** [comment]
@vfleaking uoj的沙箱是限制了线程数吗？

**Comment by vfleaking** [comment]
@riteme 其实是直接限制了不许启动新线程/进程
@Ruanxingzhi 这就很尴尬了。。。但允许多线程确实会带来很多安全性的问题。。。

**Comment by riteme** [comment]
@vfleaking QAQ是这样的啊......这个东西能不能改啊，虽然我已经不用线程了......

**Comment by vfleaking** [comment]
@riteme 好像还是能改改的……
