### ISSUE TITLE
NO uoj_work_path.h

### ISSUE THREAD

**Issue by billchenchina** [vfleaking/uoj#56]
In /judge_client/1/uoj_judger/include/uoj_env.h [(Source file)](https://github.com/vfleaking/uoj/blob/master/judge_client/1/uoj_judger/include/uoj_env.h) ,you include uoj_work_path.h .
However, there's no "uoj_work_path.h" in your repo.
Plz fix it @vfleaking

**Comment by Ruanxingzhi** [comment]
根据`docker/judge_client/install`，这个文件在动手编译之前会被创建。文件内容只有一句话：

```cpp
#define UOJ_WORK_PATH "/home/judger/judge_client/uoj_judger"
```

因此这**不是一个bug**，虽然我们不知道vfk为什么要这样做。

**Comment by billchenchina** [comment]
@Ruanxingzhi 谢谢！我们校内搭OJ 参考一下UOJ的源码，结果没找到这个文件，感谢！

**Comment by MascoSkray** [comment]
是的，如果的确没有这个文件的话，编译是会出错的。不过这么久没人反馈这个问题，当然这不是问题辣！
