### ISSUE TITLE
Markdown的表格语法

### ISSUE THREAD

**Issue by vfleaking** [vfleaking/uoj#6]
现在UOJ博客/题面的Markdown不太支持表格，像咸鱼一样。

主要是合并单元格等需求的锅。。。

**Comment by dramforever** [comment]
合并单元格可以像 mathematica 一样写 spanfromleft, spanfromabove, spanfromboth。问题当然是具体语法。。。

**Comment by Menci** [comment]
合并单元格还是 HTML 吧 ……

Markdown 的表格语法不支持这个。

**Comment by dingyx99** [comment]
HTML的适用范围广一些，但是相对来说可能复杂一些。。但是本人是支持HTML的
