### ISSUE TITLE
UOJForm的addVSelect无法对外来的选项显示错误信息

### ISSUE THREAD

**Issue by billchenchina** [vfleaking/uoj#62]
https://github.com/UniversalOJ/UOJ-System/issues/13

Thanks to @TRCYX

**Comment by vfleaking** [comment]
感谢！ 43280f92d6ee90e2250f9133772e3880ea10b0be fix 了这个问题。。
（其实线上版uoj早就修了，但我忘记我啥时候修的了，神奇）

不过我只是加了检查，没给错误提示。。毕竟能搞这种hack的都不是需要看错误提示的普通用户。。233
