### ISSUE TITLE
chrome 上 UOJ 中文字体问题

### ISSUE THREAD

**Issue by vfleaking** [vfleaking/uoj#7]
由于 Linux 等系统上没有好的中文字体，并且不知道 chrome 什么鬼不使用伪粗体，导致部分地方 UOJ 的粗体字体显示很奇怪。

求拯救，我今天才发现这个 bug。

我的 Ubuntu 14.04 和安卓手机上均出现了这个问题

**Comment by skyline48** [comment]
表示chrome没有问题

**Comment by quietshu** [comment]
（兼容性的话）推荐 font-family：
```
'Helvetica', /* Mac Latin */ 
'Arial', /* Windows, Arch, Ubuntu, Mac Latin */ 
'Source Han Sans', /* 思源黑 */
'PingFang SC', /* Mac 苹方 */ 
'Hiragino Sans GB', /* 冬青黑 */
'Microsoft YaHei UI', 'Microsoft Yahei', /* Windows 雅黑 */
'WenQuanYi Micro Hei', /* Ubuntu 文泉驿 */
'Heiti SC', 'STHeiti', 'Droid Sans', 'SimSun', /* fallbacks，华文黑，早期 iOS，安卓，中易宋 */
sans-serif;
```

为了美观可以加些其他字体…这个只用作 fallback 😄

**Comment by vfleaking** [comment]
QAQ。。。可是文泉驿微米黑没有粗体版，然后不知道什么时候chrome也不软件模拟粗体了，导致我现在的chrome（和手机上的chrome）无法显示文泉驿微米黑的粗体

**Comment by Menci** [comment]
建议添加思源黑体 Source Han Sans SC、Noto Sans CJK SC 到列表结尾。

Chromium 是有这个 BUG 的，如果给定的字体列表里没有中文字体，则自动 Fallback 到中文字体时，不会使用独立粗体，而是将正常字重的字型进行算法加粗。

我的版本：Chromium Version 51.0.2704.79 Built on Ubuntu 16.04, running on elementary 0.4 (64-bit)

**Comment by vfleaking** [comment]
不知哪天 chrome 更新了，现在这个 bug 没有了……
