### ISSUE TITLE
Help link failure

### ISSUE THREAD

**Issue by kkksc03** [vfleaking/uoj#72]
in <http://vfleaking.blog.uoj.ac/blog/7> ，these is a link in `我就只介绍最基本的功能好了。其它的自己探索吧～比如[这里]。`。This link is invalid, and can jump to a magical website. Some open source versions seem to be affected.

**Comment by vfleaking** [comment]
感谢指出。已从 http://wowubuntu.com/markdown/ 更换为 https://www.w3cschool.cn/markdownyfsm/
可在这里找到原来的链接的存档：https://web.archive.org/web/20150813173751/http://wowubuntu.com/markdown/
