### ISSUE TITLE
评论里的Mathjax的问题

### ISSUE THREAD

**Issue by hanlin-ren** [vfleaking/uoj#73]
如果评论里的回复多于一页，能在每次翻页的时候都加载Mathjax吗？

比如说最近的一个post http://a1b3c7d9.blog.uoj.ac/blog/5208

我(r_64)的回复底下的评论超过了一页，翻页的时候第二页里的Mathjax就渲染不出来了，看到的是字符串`$O(n^2)$`而不是Mathjax公式O(n²)。第二页翻回第一页的时候也有这样的问题:(

**Comment by vfleaking** [comment]
我看看咋改.jpg

**Comment by yhx-12243** [comment]
尝试着更改一下 js，其中一个解决方案是在

> https://github.com/vfleaking/uoj/blob/master/uoj/1/js/uoj.js#L1097-L1104

中传给 $.fn.long_table() 的 config 参数中增加一条：
```js
print_after_table: function() {
	return '<script type="text/javascript">MathJax.Hub.Queue(["Typeset", MathJax.Hub]);</script>';
}
```

**Comment by vfleaking** [comment]
谢谢 @yhx-12243 ！我搞了个类似的改法，线上UOJ已经修复该bug了。
