### ISSUE TITLE
关于run_program.cpp 中的问题

### ISSUE THREAD

**Issue by gerayking** [vfleaking/uoj#77]
`rp_children[n_rp_children].mode = -1` and `rp_children[n_rp_children].mode = 0` 代表什么？此处没看懂

**Comment by vfleaking** [comment]
这里的数字是表示该进程的系统调用状态，如刚启动、没有在执行系统调用、正在执行系统调用。

[新版的代码](https://github.com/vfleaking/uoj/blob/c15d08a5de1362def67980315e5bb23a774f3efc/judger/uoj_judger/run/run_program_sandbox.h#L100)参考了 strace 源码，把这个mode改名为了flags，并使用了更可读的 enum 类型来表示状态。
