### ISSUE TITLE
提答题出现Judgement Failed

### ISSUE THREAD

**Issue by suxxsfe** [vfleaking/uoj#94]
显示 Judgement Failed
应该显示每个测试点详情的地方显示 Failed to show details

problem.conf 是：
```
n_tests 10
submit_answer on
input_pre pajel
input_suf in
output_pre pajel
output_suf out
use_builtin_judger on
output_limit 500
point_score_1 10
point_score_2 10
point_score_3 10
point_score_4 10
point_score_5 10
point_score_6 10
point_score_7 10
point_score_8 10
point_score_9 10
point_score_10 10
```

既然是直接 Judgement Failed 了，那应该是没有运行 checker，所以和 chk.cpp 没关系？

启动命令是：
```
docker run --name uoj3 -dit -p 80:80 --cap-add SYS_PTRACE  uoj_back:20220527
```

好像并没有版本号，当时是 22年2月 pull 的

**Comment by suxxsfe** [comment]
Linux ubuntu-NF5280M5 5.4.0-100-generic #113~18.04.1-Ubuntu SMP Mon Feb 7 15:02:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04.2 LTS

**Comment by vfleaking** [comment]
会不会是output_limit设得太大了？judger自己是有个output limit的，必须得超过题目限制，不然选手超过题目限制的时候就会测评失败。
可以通过 judger_output_limit 调下

**Comment by suxxsfe** [comment]
> 会不会是output_limit设得太大了？judger自己是有个output limit的，必须得超过题目限制，不然选手超过题目限制的时候就会测评失败。 可以通过 judger_output_limit 调下

尝试了改成 output_limit 64 或者直接不加 output_limit ，但都仍然 judgement_fail  
而且事实上这个题的输出文件都特别小，最大不超过1M

**Comment by suxxsfe** [comment]
checker出问题可能导致 judgement_fail 吗？

**Comment by vfleaking** [comment]
checker出问题也是有可能的，不过我暂时没想到什么符合你报告的现象的情况。。

不如把完整的数据包发出来看看？或者去 UOJ 开源群私聊发我一份。

**Comment by suxxsfe** [comment]
> checker出问题也是有可能的，不过我暂时没想到什么符合你报告的现象的情况。。
> 
> 不如把完整的数据包发出来看看？或者去 UOJ 开源群私聊发我一份。

好的，qq发了

**Comment by vfleaking** [comment]
当前版本的UOJ好像是能正常评测的。
但我看了下你的 chk，第93行似乎包含了 UTF-8 字符编码下的无效字符（`value`和`%d`之间）。看起来这个文件是使用了中文标点后，以某种 UTF-8 之外的字符编码保存的？
我怀疑你下的老版本里没有妥善处理这种无效字符，从而导致了测评失败。我觉得可以把 chk 里面的无效字符去掉之后再试试

**Comment by suxxsfe** [comment]
> 当前版本的UOJ好像是能正常评测的。 但我看了下你的 chk，第93行似乎包含了 UTF-8 字符编码下的无效字符（`value`和`%d`之间）。看起来这个文件是使用了中文标点后，以某种 UTF-8 之外的字符编码保存的？ 我怀疑你下的老版本里没有妥善处理这种无效字符，从而导致了测评失败。我觉得可以把 chk 里面的无效字符去掉之后再试试

谢谢，改半角就好了，chk别人给我的之前没发现（
